#
# This file contains expected test output data generated by PBBT.
#
---
suite: diagnose-t-1
tests:
- sh: python3 /home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py /home/bodhi/Repos/Drasil/code/drasil-example/Drasil/Diagnose/inputfiles/testcase1a.txt
  stdout: ''
- sh: python3 /home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py /home/bodhi/Repos/Drasil/code/drasil-example/Drasil/Diagnose/inputfiles/testcase2a.txt
  stdout: |
    N_o has value 0.0, but is expected to be above 0.
    Traceback (most recent call last):
      File "/home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 21, in input_constraints
        raise Exception("InputError")
    Exception: InputError
- sh: python3 /home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py /home/bodhi/Repos/Drasil/code/drasil-example/Drasil/Diagnose/inputfiles/testcase2b.txt
  stdout: |
    N_o has value -12000000.0, but is expected to be above 0.
    Traceback (most recent call last):
      File "/home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 21, in input_constraints
        raise Exception("InputError")
    Exception: InputError
- sh: python3 /home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py /home/bodhi/Repos/Drasil/code/drasil-example/Drasil/Diagnose/inputfiles/testcase3a.txt
  stdout: |
    N_t has value 0.0, but is expected to be between 0 and 12000000.0 (N_o).
    Traceback (most recent call last):
      File "/home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 32, in input_constraints
        raise Exception("InputError")
    Exception: InputError
- sh: python3 /home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py /home/bodhi/Repos/Drasil/code/drasil-example/Drasil/Diagnose/inputfiles/testcase3b.txt
  stdout: |
    N_t has value -5000000.0, but is expected to be between 0 and 12000000.0 (N_o).
    Traceback (most recent call last):
      File "/home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 32, in input_constraints
        raise Exception("InputError")
    Exception: InputError
- sh: python3 /home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py /home/bodhi/Repos/Drasil/code/drasil-example/Drasil/Diagnose/inputfiles/testcase4a.txt
  stdout: |
    N_t has value 12000000.0, but is expected to be between 0 and 5000000.0 (N_o).
    Traceback (most recent call last):
      File "/home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 32, in input_constraints
        raise Exception("InputError")
    Exception: InputError
- sh: python3 /home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py /home/bodhi/Repos/Drasil/code/drasil-example/Drasil/Diagnose/inputfiles/testcase5a.txt
  stdout: |
    t_t has value 0.0, but is expected to be between 0 and 30.0 (t_p).
    Traceback (most recent call last):
      File "/home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 43, in input_constraints
        raise Exception("InputError")
    Exception: InputError
- sh: python3 /home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py /home/bodhi/Repos/Drasil/code/drasil-example/Drasil/Diagnose/inputfiles/testcase5b.txt
  stdout: |
    t_t has value -1.0, but is expected to be between 0 and 30.0 (t_p).
    Traceback (most recent call last):
      File "/home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 43, in input_constraints
        raise Exception("InputError")
    Exception: InputError
- sh: python3 /home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py /home/bodhi/Repos/Drasil/code/drasil-example/Drasil/Diagnose/inputfiles/testcase6a.txt
  stdout: |
    t_t has value 1.0, but is expected to be between 0 and 0.0 (t_p).
    Traceback (most recent call last):
      File "/home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 43, in input_constraints
        raise Exception("InputError")
    Exception: InputError
- sh: python3 /home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py /home/bodhi/Repos/Drasil/code/drasil-example/Drasil/Diagnose/inputfiles/testcase6b.txt
  stdout: |
    t_t has value 1.0, but is expected to be between 0 and -1.0 (t_p).
    Traceback (most recent call last):
      File "/home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 43, in input_constraints
        raise Exception("InputError")
    Exception: InputError
- sh: python3 /home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py /home/bodhi/Repos/Drasil/code/drasil-example/Drasil/Diagnose/inputfiles/testcase7a.txt
  stdout: |
    t_t has value 30.0, but is expected to be between 0 and 1.0 (t_p).
    Traceback (most recent call last):
      File "/home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Repos/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 43, in input_constraints
        raise Exception("InputError")
    Exception: InputError
- sh: python3 /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py
    /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/test/testcase1a.txt
  stdout: ''
- sh: python3 /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py
    /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/test/testcase2a.txt
  stdout: |
    N_o has value 0.0, but is expected to be above 0.
    Traceback (most recent call last):
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 21, in input_constraints
        raise Exception("InputError")
    Exception: InputError
- sh: python3 /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py
    /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/test/testcase2b.txt
  stdout: |
    N_o has value -12000000.0, but is expected to be above 0.
    Traceback (most recent call last):
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 21, in input_constraints
        raise Exception("InputError")
    Exception: InputError
- sh: python3 /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py
    /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/test/testcase3a.txt
  stdout: |
    N_t has value 0.0, but is expected to be between 0 and 12000000.0 (N_o).
    Traceback (most recent call last):
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 32, in input_constraints
        raise Exception("InputError")
    Exception: InputError
- sh: python3 /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py
    /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/test/testcase3b.txt
  stdout: |
    N_t has value -5000000.0, but is expected to be between 0 and 12000000.0 (N_o).
    Traceback (most recent call last):
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 32, in input_constraints
        raise Exception("InputError")
    Exception: InputError
- sh: python3 /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py
    /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/test/testcase4a.txt
  stdout: |
    N_t has value 12000000.0, but is expected to be between 0 and 5000000.0 (N_o).
    Traceback (most recent call last):
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 32, in input_constraints
        raise Exception("InputError")
    Exception: InputError
- sh: python3 /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py
    /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/test/testcase5a.txt
  stdout: |
    t_t has value 0.0, but is expected to be between 0 and 30.0 (t_p).
    Traceback (most recent call last):
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 43, in input_constraints
        raise Exception("InputError")
    Exception: InputError
- sh: python3 /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py
    /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/test/testcase5b.txt
  stdout: |
    t_t has value -1.0, but is expected to be between 0 and 30.0 (t_p).
    Traceback (most recent call last):
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 43, in input_constraints
        raise Exception("InputError")
    Exception: InputError
- sh: python3 /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py
    /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/test/testcase6a.txt
  stdout: |
    t_t has value 1.0, but is expected to be between 0 and 0.0 (t_p).
    Traceback (most recent call last):
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 43, in input_constraints
        raise Exception("InputError")
    Exception: InputError
- sh: python3 /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py
    /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/test/testcase6b.txt
  stdout: |
    t_t has value 1.0, but is expected to be between 0 and -1.0 (t_p).
    Traceback (most recent call last):
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 43, in input_constraints
        raise Exception("InputError")
    Exception: InputError
- sh: python3 /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py
    /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/test/testcase7a.txt
  stdout: |
    t_t has value 30.0, but is expected to be between 0 and 1.0 (t_p).
    Traceback (most recent call last):
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 43, in input_constraints
        raise Exception("InputError")
    Exception: InputError
- sh: python3 /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py
    /home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/test/testcase2b.txt
  stdout: |
    N_o has value -12000000.0, but is expected to be above 0.
    Traceback (most recent call last):
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/Control.py", line 20, in <module>
        InputConstraints.input_constraints(inParams)
      File "/home/bodhi/Reposnew/Drasil/code/build/Diagnose/src/python/InputConstraints.py", line 21, in input_constraints
        raise Exception("InputError")
    Exception: InputError
